"""Add book_author column to Interaction table

Revision ID: 719170cc6e30
Revises: f25cfa89e9c0
Create Date: 2023-08-18 22:23:17.076451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719170cc6e30'
down_revision = 'f25cfa89e9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('book_author', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interaction', schema=None) as batch_op:
        batch_op.drop_column('book_author')

    # ### end Alembic commands ###
